#160577479 User should be able to create and view their profile
andela/ah-shakas pull request #12
Opened 2018-10-02 08:23 UTC by Ramon3162

#### What does this PR do?
Have the user profile created on user registration.
Allows a user to update their user profile details.
#### Description of Task to be completed?
Have the following endpoints working:
```GET /api/profiles/<username>/```
```PUT /api/profiles/<username>/```
#### How should this be manually tested?
- After cloning the repo, make migrations and test the above endpoints using postman.
#### Any background context you want to provide?
- The username to be tested needs to be registered first for this to work
#### What are the relevant pivotal tracker stories?
#160577479
#### Any Necessary Screenshots
<img width="1027" alt="screen shot 2018-10-10 at 15 06 03" src="https://user-images.githubusercontent.com/28476798/46735300-8864b300-cc9e-11e8-8f92-8020515cfb7a.png">

2018-10-02 17:34 UTC, codingedward requested changes
Hi Ian, 
As we agreed to have TDD, could we kindly have tests for the profile feature? You could simply base it on the tests on the `authentication` app.

Reach out in case of any help needed.

2018-10-02 17:34 UTC, codingedward commented on authors/urls.py
> +    path('api/', include(('authors.apps.profiles.urls', 'authentication'), namespace='profiles')),
Check the second parameter passed in the `include`  tuple. From [Django's documentation](https://docs.djangoproject.com/en/2.1/ref/urls/#include), it ought to be:
```python
 include((pattern_list, app_namespace), namespace=None)
```
Just change the `authentication` to `profiles` and we'll be okay on this.

2018-10-02 20:46 UTC, koechkevin reviewed
looks good

2018-10-02 20:46 UTC, koechkevin commented on authors/settings.py
> -
I don't understand why you removed this

2018-10-07 12:05 UTC, lukorito commented on authors/apps/authentication/backends.py
>  """Configure JWT Here"""
We should probably remove this

2018-10-09 17:15 UTC, codingedward approved these changes

2018-10-09 17:16 UTC, codingedward commented
@FawazFarid, I believe this is ready for a merge.

2018-10-10 10:52 UTC, IncredibleBlackMan commented
@FawazFarid I believe this is ready for merge after you have reviewed it.

2018-10-10 16:17 UTC, koechkevin commented
This PR is ready for a merge.

2018-10-10 23:43 UTC, merged