[CHORE - 160577476] Users Verification after signup
andela/ah-shakas pull request #15
Opened 2018-10-03 10:06 UTC by james-chege

### What does this PR do?

-  Verify user after signup
### Description of Task to be completed?
- The users can verify their account after signup.
- A link is sent to the email. After the user clicks the link they will be able to activate their account.
 `Note: Before clicking the link, the account is inactive`
### How should this be manually tested?
- Clone [ah-shakas](https://github.com/andela/ah-shakas) repo `$ git clone https://github.com/andela/ah-shakas.git`
- export db credentials. please note that there is no spaces before and after `=`

```
      export DB_NAME="name of your database"
      export DB_PASSWORD="passord to your database user"
      export DB_HOST="your local server eg (127.0.0.1)"
      export DB_USER="your database username eg (postgres)"
```
_Note- if you have no password set for your database user leave the password field blank i.e `export DB_PASSWORD=""`_
- On the project's root directory run `python manage.py runserver`
- send a `POST` request to the server http://127.0.0.1:8000/users/ whith the following in the body.
```
{
  "user":{
    "email":"email@domain.com",
    "username":"simple username",
    "password":"AlphaNumericPassword"
  }
}
```
- Done! 🙂
### What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/160577476

2018-10-03 10:59 UTC, koechkevin commented
please resolve merge conflicts

2018-10-03 11:20 UTC, james-chege commented
> please resolve merge conflicts

Thanks. Will resolve ASAP

2018-10-12 05:24 UTC, FawazFarid requested changes

2018-10-12 05:24 UTC, FawazFarid commented on authors/apps/authentication/views.py
> +                )
this indentation, seems a bit off, let's do it this way:
```
send_mail(
    'Verify your email',
    'Please verify your account.',
    'no-reply@authors-heaven.com',
    [user_email],
    html_message = body,
    fail_silently=False,
)
```

2018-10-12 05:24 UTC, FawazFarid commented on authors/apps/authentication/views.py
> +        return_message = {"Message":"Thank you for registering at Authors heaven. To start using authors heaven, go to your email and click the confirmation link which we haves sent to you :D"}
this line is too long

2018-10-12 05:24 UTC, FawazFarid commented on authors/settings.py
> +DEFAULT_DOMAIN = 'http://127.0.0.1:8000'
what if we push this to production, would it work?

2018-10-12 05:24 UTC, FawazFarid commented on authors/settings.py
> +# DEFAULT_DOMAIN = 'https://www.yoursite.com:port'
Do we need this comment?

2018-10-12 11:50 UTC, james-chege commented on authors/apps/authentication/views.py
> +                )
Cool. Will rectify this.

2018-10-12 11:53 UTC, james-chege commented on authors/settings.py
> +DEFAULT_DOMAIN = 'http://127.0.0.1:8000'
Not sure, let me use the official link from Lukorito to avoid surprises.

2018-10-12 12:25 UTC, ibetween commented on authors/settings.py
> +# DEFAULT_DOMAIN = 'https://www.yoursite.com:port'
Noted. will get rid of it.

2018-10-14 07:36 UTC, lukorito commented
Some great work in modifying the tests. This should be merged so that all incoming tests to follow suite @FawazFarid

2018-10-15 09:35 UTC, FawazFarid approved these changes

2018-10-16 09:38 UTC, merged