Ft password reset 160577477
andela/ah-shakas pull request #16
Opened 2018-10-03 16:50 UTC by koechkevin

#### What does this PR do?
- Enables a user to reset password using a link sent via email
#### Description of Task to be completed? 
- Users are able to post requests to reset their passwords.
- A token is generated and sent to the user via e mail.
- The token will be used by the user to reset password
- Tests for the functionality are also included.
- Have the following endpoints working
```
POST /api/users/email_sent    body = {"email":email}
```
```
PUT users/password_reset?token= .  body = {"email":email, "password":new_password}
```
#### How should this be manually tested?
- After cloning the repo, set your database variables on .env file.
- Add the following lines to your .env file
```
export EMAIL_HOST=smtp.sendgrid.net
export EMAIL_HOST_USER=shakas
export EMAIL_HOST_PASSWORD=Shakas123
export EMAIL_PORT=587
```
- run the application python manage.py runserver
- test your endpoint.
- NOTE the email you receive has a google url but we are only interested in the token attached to it. 
- from the url in the mail, copy the url from ?token= and paste it on the reset password endpoint to ensure it works.
#### Any background context you want to provide?
- The email sent uses a template obtained from http://leemunroe.github.io/responsive-html-email-template/email.html
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/160577476

2018-10-05 06:36 UTC, codingedward reviewed
Hello @koechkevin, I have gone through your implementation and highlighted a few changes based on the code review we had

2018-10-05 06:36 UTC, codingedward commented on authors/apps/authentication/test_password_reset.py
> +        self.assertEqual(response.content, b'{"user": {"message": "The Email provided is not registered"}}')
Let's have this as `The email provided is not registered instead`. Note the casing please.

2018-10-05 06:36 UTC, codingedward commented on authors/apps/authentication/views.py
> +            if request.data['email'].strip() == "":
We agreed that since Django will strip all text inputs, this would be unnecessary.

2018-10-05 06:36 UTC, codingedward commented on authors/apps/authentication/views.py
> +        except KeyError:
I think since this is being checked in the serializer already where we have `required=True`, this check would be unnecessary.

2018-10-05 06:36 UTC, codingedward commented on authors/apps/authentication/views.py
> +        user = User.objects.filter(email=email).first()
We have ensured the email is unique. Therefore we can have this as `user = User.objects.get(email=email)`

2018-10-05 06:36 UTC, codingedward commented on authors/apps/authentication/views.py
> +            'link': 'http://127.0.0.1:8000/api/users/password_reset?token=' + token,
Let's have the base URL coming from the environment variables  through the `settings.py`

2018-10-05 06:36 UTC, codingedward commented on authors/apps/authentication/views.py
> +        send_mail(subject, "Password Reset", "no-reply@Authors-Haven.com", [email], html_message=body)
Same here, let's have the email coming from the environment variables.

2018-10-10 11:26 UTC, IncredibleBlackMan reviewed
This PR looks good to me. @koechkevin I must say you have done quite some work here.

2018-10-10 12:54 UTC, lukorito commented
Great job on the UI

2018-10-11 13:12 UTC, FawazFarid requested changes
This looks good to me

2018-10-11 13:12 UTC, FawazFarid commented on authors/apps/authentication/test_password_reset.py
> +    def test_email_field_missing(self):
nice work here with the tests @koechkevin. Can we add more test for invalid email e.g. when a user enters something like `fawwaz.ali` instead `fawaz.ali@andela.com`

2018-10-12 04:57 UTC, FawazFarid approved these changes

2018-10-13 18:34 UTC, merged