#160577482 Implement comments(CRUD)
andela/ah-shakas pull request #23
Opened 2018-10-09 08:20 UTC by gloriaodipo

*What does this PR do*
- This PR implements CRUD functionality for comments feature

*Description of task to be completed*
-Only authenticated users should be able to comment on articles.
- Successive comments should be threaded
- Comments should be timestamped
*Endpoints*
'articles/<slug>/comments/'
'articles/<slug>/comments/<int:id>/
*Post comment*
![image](https://user-images.githubusercontent.com/34505753/46655706-03519f00-cbb5-11e8-98e6-279fad07cae2.png)

*Get one comment*
![image](https://user-images.githubusercontent.com/34505753/46655761-23815e00-cbb5-11e8-93f6-2ac883dc25f7.png)

*Get all comments*
![image](https://user-images.githubusercontent.com/34505753/46655811-43188680-cbb5-11e8-9f9d-34efe5b8744b.png)

2018-10-11 12:40 UTC, FawazFarid requested changes

2018-10-11 12:40 UTC, FawazFarid commented on authors/apps/articles/admin.py
> +from .models import ArticlesModel,Comment
Insert a space between the comma and Comment

2018-10-11 12:40 UTC, FawazFarid commented on authors/apps/articles/models.py
> +               )
the indentation for this seems a bit off to me, I'd do it like this :
```
parent = models.ForeignKey(
   'self',
    null=True,
    blank=True,
    related_name='threads',
    on_delete=models.CASCADE
)
```
I'm not super sure but this looks more readable 😅, what do you think?

2018-10-11 12:40 UTC, FawazFarid commented on authors/apps/articles/serializers.py
> +                'updated_at': self.format_date(thread.updated_at)}  for thread in instance.threads.all()]
the closing curly bracker `}` should be in the next line, and the `]` should be on the next line after e.g
```
...
        'updated_at': self.format_date(thread.updated_at)
    } for thread in instance.threads.all()
]

```

2018-10-11 13:21 UTC, gloriaodipo commented on authors/apps/articles/admin.py
> +from .models import ArticlesModel,Comment
Noted

2018-10-11 13:22 UTC, gloriaodipo commented on authors/apps/articles/models.py
> +               )
Yeah, sure 😅

2018-10-12 05:03 UTC, FawazFarid approved these changes

2018-10-12 05:12 UTC, merged