#160577485 Implement favourating and unfavourating articles
andela/ah-shakas pull request #28
Opened 2018-10-11 16:01 UTC by caveinn

#### What does this PR do?
Have the implementation for favourating and unfavourating features.
#### Description of Task to be completed?

Have the following end points working 

```POST /api/articles/<slug>/favourite```
Which favourates an artcle by adding the user and article to a database table

```DELETE /api/articles/<slug>/favourite```
This implements unfavouratin by deleting the user and article pair from the table

Also when a user gets an article they get a field informing theme if they have favourited it or not.
#### How should this be manually tested?
after cloning the repo  you run:
```python manage.py  test authors/apps/articles/tests/```

on Postman test the above endpoint by adding:
*key*:Authorization *value*: token

the token to be goten from the signup or login endpoint

#### Any background context you want to provide?
This is an implemantation similar to bookmarking an article to access later.

#### What are the relevant pivotal tracker stories?
#160577485
#### Screenshots 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/30701246/46817362-a1955e80-cd87-11e8-8469-397f355b8517.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/30701246/46817275-7f034580-cd87-11e8-9793-8599d516a5ae.png">

2018-10-11 17:09 UTC, james-chege commented
@caveinn Nice work! 🎆 Your implementation is awesome though on the first screenshot, after favouriting the article the field `favourited` seems to be false. This could be fixed. Keep up the good spirit! 🕯

2018-10-11 18:08 UTC, caveinn commented
Thanks @james-chege I have fixed that

2018-10-11 18:28 UTC, ibetween approved these changes

2018-10-12 12:09 UTC, Ramon3162 commented on authors/apps/articles/views.py
> +            data = {
Hey @caveinn, I have gone through the PR and I believe there is a better way you could have handled these errors, use renderers instead to handle the responses. However, your implementation is pretty good.

2018-10-12 12:09 UTC, Ramon3162 commented on authors/apps/articles/views.py
> +                    "errors":{
Ditto 😄

2018-10-12 16:08 UTC, lukorito requested changes

2018-10-12 16:08 UTC, lukorito commented on authors/apps/articles/serializers.py
> +                message = "you have already favourited this article"
Title case maybe? In the message

2018-10-12 16:08 UTC, lukorito commented on authors/apps/articles/tests/test_favourite.py
> +        response = self.client.post(self.signup_url, self.user, format='json')
👍

2018-10-12 17:49 UTC, caveinn commented
@lukorito I believe I have implemented your feedback

2018-10-17 16:07 UTC, lukorito commented
Hi @caveinn. Thanks for the working on the review. However, I think PR can be improved in terms of grammar. Here are some of my recommendations:
- Some bullets, like in the prerequisite are off, you can fix that.
- Arrange the sentences with full stops and capitalizations.
- Use make titles, for instance,`prerequisites:` be distinguishable from procedure maybe by using bolding or adding space at the beginning.
- Use bullets or numbering in arranging the steps

2018-10-17 16:18 UTC, caveinn commented
@Kitika I have implemented the changes

2018-10-17 16:19 UTC, lukorito approved these changes

2018-10-18 07:27 UTC, merged